name: 'AWS S3 Sync Action'
description: 'Sync files to s3 with compare and create cloudfront invalidation.'
author: wxul
inputs:
  aws_bucket_name:
    description: Bucket name
    required: true

  aws_cloudfront_distribution_id:
    description: Cloudfront distribution id
    required: false

  compare:
    description: Compare ETag with s3 existed files
    required: false
    default: "true"

  source:
    description: Source directory
    required: true

  concurrent:
    description: Concurrent count
    required: false
    default: '8'

  if_has_failed:
    description: Choose how to exit the action if some files upload failed (fail or ignore)
    default: ignore

outputs:
  error_message:
    description: The error message, if an error occurs
  invalidation_id:
    description: Cloudfront invalidation id if Created
  uploaded_files:
    description: Uploaded files

runs:
  using: 'node16'
  main: 'lib/index.js'
